### ISSUE TITLE
How to add this hack to existing plugin

### ISSUE THREAD

**Issue by pedy711** [tbroyer/gwt-devserver#2]
I have a working project with GWT and Spring boot Server. I want to run GWT on HTTPS. How can I benefit from this project? Do I have to add your DevServer.java to my project? if yes, where?

Thank you in advance

**Comment by tbroyer** [comment]
You can get a `-SNAPSHOT` (or `master-SNAPSHOT`) version from [JitPack](https://jitpack.io/#tbroyer/gwt-devserver), and you can use it in a Maven project with the [exec-maven-plugin](http://www.mojohaus.org/exec-maven-plugin/).

Note that you'll have to load your application "through" the devserver, i.e. without HTTPS; so it would probably actually give you nothing, and you'd better just run your Spring Boot server without HTTPS.  
Fwiw, the devserver does not change how Super Dev Mode works: the CodeServer is still run, listening to a separate port, without HTTPS. What the devserver gives you is that it would proxy an HTTP request to your HTTPS server; it does not add HTTPS toe Super Dev Mode.

**Comment by pedy711** [comment]
As you explained, I added gwt-devserver maven dependency using JitPack. But I don't know how to run it using exec-maven-plugin.

I normally run my gwt project using:

    mvn gwt:devmode -Pgwt-dev

which compile gwt module from my "gwt-dev" profile in maven file.

but I get the following error when trying to run it on Spring Boot HTTPS server:

    Couldn't load app from Super Dev Mode. server at http://192.168.56.1:9876. Please make sure this server is ready. Do you want to try again?

I also asked my question on stackoverflow:

Would be great if you take a look at it:

[Link on stackoverflow](https://stackoverflow.com/questions/47226884/how-to-run-smartgwt-on-ssl-pre-configured-spring-boot-server)

**Comment by tbroyer** [comment]
You can try something like:
```xml
<plugin>
  <groupId>org.codehaus.mojo</groupId>
  <artifactId>exec-maven-plugin</artifactId>
  <version>1.6.0</version>
  <configuration>
    <mainClass>net.ltgt.gwt.devserver.DevServer</mainClass>
    <!-- Same you have configured for `gwt:devmode`, default to the same 'runtime' value:
    <classpathScope>runtime</classpathScope>
    -->
    <arguments>
      <arg>-workDir</arg><arg>${project.build.directory}/gwt/codeserver</arg>
      <!-- Proxy to your Spring Boot server -->
      <arg>-proxyTo</arg><arg>https://localhost:9999</arg>
      <!-- last argument is your module name -->
      <arg>net.example.app.Application</arg>
    </arguments>
  </configuration>
</plugin>
```
and run with `mvn exec:java` (probably `-Pgwt-dev` too); note that in a multi-module project, this needs to be run in the GWT app module (which means you might have to `mvn install` other modules used as dependencies).

This will (should) launch a server at `http://localhost:8888/` that proxies all requests to `https://localhost:9999` (your Spring Boot server; change the port if needed) but intercepts requests to your `*.nocache.js` to serve the SuperDevMode stub (the code server still runs on port 9876, but it's no longer a problem since you don't have HTTPS in the equation, hidden by the reverse proxy)

It might be easier to just use `gwt:codeserver` but setup a lightweight reverse-proxy (e.g. [`devd`](https://github.com/cortesi/devd) with `devd -p 8888 https://localhost:9999`); you'll have almost the same end-result. Or, as I said earlier, disable HTTPS on the Spring Boot server.

**Comment by pedy711** [comment]
I made a small progress, but for some reason, this config doesn't start the server on `http://localhost:8888/App.html`

It only runs the `GWT Code Server` on port 9876 where it says to drag the bookmarklets to bookmark bar of the browser.



```
<profile>
			<id>exec-dev</id>
			<build>
				<resources>
					<resource>
						<directory>src/main/java</directory>
					</resource>
				</resources>
				<plugins>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>exec-maven-plugin</artifactId>
						<version>1.6.0</version>
						<configuration>
							<moduleName>com.jdisc.mdm.App</moduleName>
							<moduleShortName>App</moduleShortName>
							<startupUrls>
								<startupUrl>App.html</startupUrl>
							</startupUrls>
							<mainClass>net.ltgt.gwt.devserver.DevServer</mainClass>
							<arguments>
								<arg>-workDir</arg>
								<arg>${basedir}/../MdmServer/target/classes/static</arg>
								<!-- Proxy to your Spring Boot server -->
								<arg>-proxyTo</arg>
								<arg>https://localhost:443</arg>
								<!-- last argument is your module name -->
								<arg>com.jdisc.mdm.App</arg>
							</arguments>
							<devmodeArgs>
								<arg>-bindAddress</arg>
								<arg>0.0.0.0</arg>
							</devmodeArgs>
							<classpathScope>compile</classpathScope>
							<devmodeWorkDir>${basedir}/../MdmServer/target/classes/static</devmodeWorkDir>
							<launcherDir>${basedir}/../MdmServer/target/classes/static</launcherDir>
							<warDir>${basedir}/../MdmServer/target/classes/static</warDir>
							<webappDirectory>${basedir}/../MdmServer/target/classes/static</webappDirectory>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
```

I think the problem is not the redirection/proxy to the Spring Boot HTTPS server, but rather missing files from the right location/directory for the server in order to load them and show them on the browser because I already tried this with Spring Boot redirection where it redirects you from localhost:8080 or any other port to my https server port successfully. It just doesn't compile the gwt code and instead throws the following error which I mentioned earlier:

`Couldn't load app from Super Dev Mode. server at http://192.168.56.1:9876. Please make sure this server is ready. Do you want to try again?`

P.S: HTTPS for the Spring Boot Server is a requirement of the project.

**Comment by tbroyer** [comment]
> P.S: HTTPS for the Spring Boot Server is a requirement of the project.

I understand it could be a requirement in production, but that doesn't mean you couldn't disable it for development.

Anyway, if you want to discuss this further, please use the [forum](https://groups.google.com/forum/#!forum/google-web-toolkit)
